@BASE_URL = http://127.0.0.1:8000

###
# auth.register
POST {{ BASE_URL }}/api/auth/register
Content-Type: application/json

{
    "email": "abc12@abc.com",
    "name": "tester",
    "password": "rewq1234"
}


###
# @name authorization
POST {{ BASE_URL }}/api/auth/login
Content-Type: application/json

{
    "email": "asj214@naver.com",
    "password": "rewq1234"
}


###
@token = {{ authorization.response.body.token }}

###
# auth.me
GET {{ BASE_URL }}/api/auth/me
Content-Type: application/json
Authorization: Token {{ token }}


### 
# customer register
POST {{ BASE_URL }}/api/customers/register
Content-Type: application/json

{
    "email": "sjahn@ktown4u.com",
    "name": "tester",
    "password": "rewq1234"
}


###
# @name login
POST {{ BASE_URL }}/api/customers/login
Content-Type: application/json

{
    "email": "sjahn@ktown4u.com",
    "password": "rewq1234"
}


###
@bearer = {{ login.response.body.token }}


###
# auth.me
GET {{ BASE_URL }}/api/customers/me
Content-Type: application/json
Authorization: Bearer {{ bearer }}